---
version: '3'

services:
  petio:
    hostname: 'petio'
    container_name: 'petio'
    user: '${ID}:${ID}'
    environment:
      - 'PGID=${ID}'
      - 'PUID=${ID}'
      - 'TZ=${TZ}'
    image: 'ghcr.io/petio-team/petio:latest'
    restart: 'unless-stopped'
    depends_on:
      - 'mongo'
    ports:
      - '127.0.0.1:7444:7777'
    networks:
      - proxy
    security_opt:
      - 'no-new-privileges:true'
    volumes:
      - '/opt/appdata/petio/config:/app/api/config'
      - '/opt/appdata/petio/logs:/app/logs'
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=proxy'
      - 'dockupdater.enable=true'
      - 'traefik.http.routers.petio-rtr.entrypoints=https'
      - 'traefik.http.routers.petio-rtr.rule=Host(`petio.${DOMAIN}`)'
      - 'traefik.http.routers.petio-rtr.tls=true'
      - 'traefik.http.routers.petio-rtr.tls.certresolver=dns-cloudflare'
      - 'traefik.http.routers.petio-rtr.middlewares=chain-authelia@file'
      - 'traefik.http.routers.petio-rtr.service=petio-svc'
      - 'traefik.http.services.petio-svc.loadbalancer.server.port=7777'

  mongo:
    hostname: 'petiomongo'
    image: 'mongo:latest'
    container_name: 'petiomongo'
    ports:
      - '27017:27017'
    networks:
      - proxy
    user: '${ID}:${ID}'
    volumes:
      - '/opt/appdata/petio/db:/data/db'

networks:
  proxy:
    driver: bridge
    external: true
